package dao;

import java.sql.Connection;
import java.sql.SQLException;

import AirCrash.Air.Airline;
import AirCrash.Air.Airplane;
import mappers.IMapResultSetIntoEntity;

public class AirlineRepository extends RepositoryBase<Airline> {

	public AirlineRepository(Connection connection, IMapResultSetIntoEntity<Airline> mapper) {
		super(connection,mapper);
	}
	
	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE Airplane("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(50)" 
				+ ")";
	}

	@Override
	protected String tableName() {
		return "Airline";
	}

	protected String insertSql() {
		return "INSERT INTO Airline(name) VALUES (?)";
	}

	protected String updateSql() {
		return "UPDATE Airline SET (name)=(?) WHERE id=?";
	}


	@Override
	protected void setUpdate(Airline entity) throws SQLException {
		update.setString(1, entity.name());
		
	}

	@Override
	protected void setInsert(Airline entity) throws SQLException {
		insert.setString(2, entity.name());
	}
	
}

