package dao;

import java.sql.Connection;
import java.sql.SQLException;

import mappers.IMapResultSetIntoEntity;
import AirCrash.Air.Airplane;

public class AirplaneRepository extends RepositoryBase<Airplane> {

	public AirplaneRepository(Connection connection, IMapResultSetIntoEntity<Airplane> mapper) {
		super(connection,mapper);
	}
	
	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE people("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "seats int," + "model varchar(50)" + ")";
	}

	@Override
	protected String tableName() {
		return "Airplane";
	}

	protected String insertSql() {
		return "INSERT INTO Airplane(seats, model) VALUES (?,?)";
	}

	protected String updateSql() {
		return "UPDATE people SET (seats, model)=(?,?) WHERE id=?";
	}


	@Override
	protected void setUpdate(Airplane entity) throws SQLException {
		update.setString(1, entity.seats());
		update.setString(2, entity.model());
		
	}

	@Override
	protected void setInsert(Airplane entity) throws SQLException {
		insert.setInt(1, entity.seats());
		insert.setString(2, entity.model());
	}
	
}
