package dao;

import java.sql.Connection;
import java.sql.SQLException;

import AirCrash.Air.Reservation;
import mappers.IMapResultSetIntoEntity;

public class ReservationRepository extends RepositoryBase<Reservation> {

	public ReservationRepository(Connection connection, IMapResultSetIntoEntity<Reservation> mapper) {
		super(connection,mapper);
	}
	
	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE Airplane("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "journeyId bigint" 
				+ "price double" 
				+ "numberOfTickets int" 
				+ ")";
	}

	@Override
	protected String tableName() {
		return "Reservation";
	}

	protected String insertSql() {
		return "INSERT INTO Reservation(journeyId, price, numerOfTickets) VALUES (?,?,?)";
	}

	protected String updateSql() {
		return "UPDATE Reservation SET (journeyId, price, numerOfTickets)=(?,?,?) WHERE id=?";
	}


	@Override
	protected void setUpdate(Reservation entity) throws SQLException {
		update.setInt(1, entity.journeyId());
		update.setDouble(2, entity.price());
		update.setInt(3, entity.numerOfTickets());
		
	}

	@Override
	protected void setInsert(Reservation entity) throws SQLException {
		insert.setInt(1, entity.journeyId());
		insert.setDouble(2, entity.price());
		insert.setInt(3, entity.numerOfTickets());
	}
	
}